/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import house from "./assets/Immers Home new apt.glb"

export default function Model(props) {
  // const { nodes, materials } = useGLTF(house);
  const gltf = useGLTF(house);
  return (
    <primitive object={gltf.scene} />
  );
}

useGLTF.preload(house);


